### ISSUE TITLE
Setting text font.

### ISSUE THREAD

**Issue by reindex-ot** [chinosk6/Trainers-Legend-G-External-Plugin#3]
There is a problem with Chinese fonts being specified when displaying Japanese.
We would like to have a setting that allows Japanese fonts to be loaded.

![UI_font](https://github.com/chinosk6/Trainers-Legend-G-External-Plugin/assets/32851879/2490093e-5d94-4b01-9e3d-c70a764b951a)

**Comment by chinosk6** [comment]
The default font is Microsoft Yahei (`msyh`). Do you know what's the default Japanese font in Windows?

**Comment by reindex-ot** [comment]
Japanese font is Tahoma (8pt) or Yu Gothic UI.

**Comment by chinosk6** [comment]
The first image is `Yu Gothic`, the second is `Yu Gothic UI`. Which one should we choose?

![image](https://github.com/chinosk6/Trainers-Legend-G-External-Plugin/assets/74499927/2e23f188-1538-4eba-a6c8-f2a57f97e403)
![image](https://github.com/chinosk6/Trainers-Legend-G-External-Plugin/assets/74499927/d3beba2f-8277-4aa0-8323-907fd93d8c38)

**Comment by reindex-ot** [comment]
Yu Gothic UI.

**Comment by chinosk6** [comment]
Updated. Binary File: [legend_g_plugin.exe](https://github.com/chinosk6/Trainers-Legend-G/blob/main/resources/legend_g_plugin.exe)

**Comment by reindex-ot** [comment]
Nice, I checked.
I would also suggest adjusting the width of the spin box and the path box.

![GUI_checked](https://github.com/chinosk6/Trainers-Legend-G-External-Plugin/assets/32851879/817490f5-5445-4ae8-bab0-951e31afab4b)
