### ISSUE TITLE
繁中系統下使用簡中譯文問題

### ISSUE THREAD

**Issue by hoho97** [chinosk6/Trainers-Legend-G-External-Plugin#6]
不知發哪裡所以在這問

我是繁中系統用戶，因為繁中烤肉大佬烤得比較慢想搶先看簡中的新劇情所以決定先換成簡中版嚐鮮。
但是把繁中版砍掉後重新下載簡中版，每次打開都要我更新一大串繁中譯文
![image](https://github.com/chinosk6/Trainers-Legend-G-External-Plugin/assets/18360960/265e3309-f2fa-4ca4-b9e8-d3860ae167ad)

我猜應該是Localized那邊的API Endpoint仍然指向繁中譯文倉庫的問題
可是epconf.json裡files_api_endpoint是空的
![image](https://github.com/chinosk6/Trainers-Legend-G-External-Plugin/assets/18360960/3c5c23c0-bf85-48bd-9406-2ac7ae4a7458)

目前是自己手動把譯文倉庫的文本手動下載來替換，但這方法感覺比較蠢
如果想讓插件更新簡中的譯文，不知道需要做什麼？

**Comment by chinosk6** [comment]
主页有一个 更改 API，修改为 `https://uma.bbq.chinosk6.cn` 即可
